### ISSUE TITLE
c99 error

### ISSUE THREAD

**Issue by paizzj** [UlordChain/UlordChain#16]
在 redhat 4.8.5-16, 编译的时候，有  for循环 初始变量定义出错，提示只有c99规范才可以 在for循环中定义初始变量。

我们是否把for 循环初始变量外提，或者提示 只支持c99编译器。

这个错误主要是在这几个文件提示，
src/hello/Pow.c      
src/hello/c_crc32.c
src/hello/c_ripemd160.c

**Comment by jxinhu** [comment]
能提供详细的编译环境和错误信息吗？

**Comment by llbec** [comment]
You need at least **gcc 4.7** to have "_-std=c11_" supported. Thanks for your suggest，we‘ll add tips for the version of gcc.’
