### ISSUE TITLE
22号上公链后，怎样从测试链换到公链？

### ISSUE THREAD

**Issue by coolhty** [UlordChain/UlordChain#22]
现在同步的都是测试链，上公链后怎样换到公链呢？

**Comment by lialvin** [comment]
你好 ，需要重新从官网下载对应的程序。如果只是为了挖矿，没必要跑windows的全节点。可以直接使用矿机。 如果学习用的，可以参考我们的github上的代码，欢迎随时提问题。后期我们会出各种基于区块链的应用。比如优享 ，可以基于手机钱包直接使用。

**Comment by coolhty** [comment]
好的，谢谢，我在试试搭建矿池。
