### ISSUE TITLE
加了testnet=0后无法更新区块是正常的吗？

### ISSUE THREAD

**Issue by coolhty** [UlordChain/UlordChain#23]
testnet=0是不是使用公链，这个版本是不是可以在公链上使用的版本呢？

**Comment by llbec** [comment]
是的，不过现在公链没有正式上线，因此现在无法更新区块。
具体上线时间，请关注官网https://ulord.org/或者5月22日Ulord发布会，谢谢！

**Comment by coolhty** [comment]
@bicliu   重启一下程序就要重新同步数据，是不是配置有问题？
配置如下：
testnet=1
rpcuser=ulordpool
rpcpassword=ulordpool
txindex=1
addressindex=1
spentindex=1
timestampindex=1
reindex=1

**Comment by llbec** [comment]
reindex=0
