### ISSUE TITLE
make的时候报错，麻烦看一下

### ISSUE THREAD

**Issue by hozyu12** [UlordChain/UlordChain#24]
[root@localhost build]# make
Scanning dependencies of target cryptoHello
[  1%] Building C object src/crypto/CMakeFiles/cryptoHello.dir/c_aes128.c.o
[  3%] Building C object src/crypto/CMakeFiles/cryptoHello.dir/blake2s.c.o
[  4%] Building C object src/crypto/CMakeFiles/cryptoHello.dir/c_blake2s256.c.o
[  6%] Building C object src/crypto/CMakeFiles/cryptoHello.dir/c_camellia128.c.o
[  7%] Building C object src/crypto/CMakeFiles/cryptoHello.dir/common.c.o
[  9%] Building C object src/crypto/CMakeFiles/cryptoHello.dir/c_crc32.c.o
[ 10%] Building C object src/crypto/CMakeFiles/cryptoHello.dir/c_des.c.o
[ 12%] Building C object src/crypto/CMakeFiles/cryptoHello.dir/c_gost.c.o
[ 13%] Building C object src/crypto/CMakeFiles/cryptoHello.dir/keccak1600.c.o
[ 15%] Building C object src/crypto/CMakeFiles/cryptoHello.dir/c_haval5_256.c.o
[ 16%] Building C object src/crypto/CMakeFiles/cryptoHello.dir/c_hmac_md5.c.o
[ 18%] Building C object src/crypto/CMakeFiles/cryptoHello.dir/jtr_crc32.c.o
[ 20%] Building C object src/crypto/CMakeFiles/cryptoHello.dir/jtr_gost.c.o
[ 21%] Building C object src/crypto/CMakeFiles/cryptoHello.dir/jtr_haval.c.o
[ 23%] Building C object src/crypto/CMakeFiles/cryptoHello.dir/jtr_skein.c.o
[ 24%] Building C object src/crypto/CMakeFiles/cryptoHello.dir/my_time.c.o
[ 26%] Building C object src/crypto/CMakeFiles/cryptoHello.dir/oneWayFunction.c.o
/var/tmp/ulordrig/src/crypto/oneWayFunction.c:36:2: 警告：初始值设定周围缺少花括号 [-Wmissing-braces]
  "SHA3-256",    crypto_sha3_256,
  ^
/var/tmp/ulordrig/src/crypto/oneWayFunction.c:36:2: 警告：(在‘funcInfor[0]’的初始化附近) [-Wmissing-braces]
[ 27%] Building C object src/crypto/CMakeFiles/cryptoHello.dir/PoW.c.o
/var/tmp/ulordrig/src/crypto/PoW.c: 在函数‘initWorkMemory’中:
/var/tmp/ulordrig/src/crypto/PoW.c:30:24: 警告：此函数中的‘*((void *)&randBuffer+72).__x’在使用前可能未初始化 [-Wmaybe-uninitialized]
  struct my_rand48_data randBuffer[4];
                        ^
/var/tmp/ulordrig/src/crypto/PoW.c:30:24: 警告：此函数中的‘*((void *)&randBuffer+48).__x’在使用前可能未初始化 [-Wmaybe-uninitialized]
/var/tmp/ulordrig/src/crypto/PoW.c:30:24: 警告：此函数中的‘*((void *)&randBuffer+24).__x’在使用前可能未初始化 [-Wmaybe-uninitialized]
/var/tmp/ulordrig/src/crypto/PoW.c:30:24: 警告：此函数中的‘randBuffer.__x’在使用前可能未初始化 [-Wmaybe-uninitialized]
[ 29%] Building C object src/crypto/CMakeFiles/cryptoHello.dir/c_rc4.c.o
[ 30%] Building C object src/crypto/CMakeFiles/cryptoHello.dir/c_ripemd160.c.o
[ 32%] Building C object src/crypto/CMakeFiles/cryptoHello.dir/c_sha1.c.o
[ 33%] Building C object src/crypto/CMakeFiles/cryptoHello.dir/c_sha3_256.c.o
[ 35%] Building C object src/crypto/CMakeFiles/cryptoHello.dir/c_sha256.c.o
[ 36%] Building C object src/crypto/CMakeFiles/cryptoHello.dir/c_sha512.c.o
[ 38%] Building C object src/crypto/CMakeFiles/cryptoHello.dir/c_skein512_256.c.o
[ 40%] Building C object src/crypto/CMakeFiles/cryptoHello.dir/c_whirlpool.c.o
[ 41%] Building CXX object src/crypto/CMakeFiles/cryptoHello.dir/cryptoHello.cpp.o
Linking CXX static library libcryptoHello.a
[ 41%] Built target cryptoHello
Scanning dependencies of target cpuid
[ 43%] Building C object src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/cpuid_main.c.o
[ 44%] Building C object src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/asm-bits.c.o
[ 46%] Building C object src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/recog_amd.c.o
[ 47%] Building C object src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/recog_intel.c.o
[ 49%] Building C object src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/libcpuid_util.c.o
Linking C static library libcpuid.a
[ 49%] Built target cpuid
Scanning dependencies of target ulordrig
[ 50%] Building CXX object CMakeFiles/ulordrig.dir/src/api/Api.cpp.o
[ 52%] Building CXX object CMakeFiles/ulordrig.dir/src/api/ApiState.cpp.o
[ 53%] Building CXX object CMakeFiles/ulordrig.dir/src/api/NetworkState.cpp.o
[ 55%] Building CXX object CMakeFiles/ulordrig.dir/src/App.cpp.o
In file included from /var/tmp/ulordrig/src/workers/Workers.h:35:0,
                 from /var/tmp/ulordrig/src/App.cpp:42:
/var/tmp/ulordrig/src/net/JobResult.h: 在成员函数‘uint64_t JobResult::actualDiff() const’中:
/var/tmp/ulordrig/src/net/JobResult.h:70:71: 警告：提领类型双关的指针将破坏强重叠规则 [-Wstrict-aliasing]
         return Job::toDiff(reinterpret_cast<const uint64_t*>(result)[3]);
                                                                       ^
[ 56%] Building CXX object CMakeFiles/ulordrig.dir/src/Console.cpp.o
[ 58%] Building CXX object CMakeFiles/ulordrig.dir/src/log/ConsoleLog.cpp.o
[ 60%] Building CXX object CMakeFiles/ulordrig.dir/src/log/FileLog.cpp.o
[ 61%] Building CXX object CMakeFiles/ulordrig.dir/src/log/Log.cpp.o
[ 63%] Building CXX object CMakeFiles/ulordrig.dir/src/Mem.cpp.o
[ 64%] Building CXX object CMakeFiles/ulordrig.dir/src/net/Client.cpp.o
In file included from /var/tmp/ulordrig/src/net/Client.cpp:47:0:
/var/tmp/ulordrig/src/net/JobResult.h: 在成员函数‘uint64_t JobResult::actualDiff() const’中:
/var/tmp/ulordrig/src/net/JobResult.h:70:71: 警告：提领类型双关的指针将破坏强重叠规则 [-Wstrict-aliasing]
         return Job::toDiff(reinterpret_cast<const uint64_t*>(result)[3]);
                                                                       ^
[ 66%] Building CXX object CMakeFiles/ulordrig.dir/src/net/Job.cpp.o
[ 67%] Building CXX object CMakeFiles/ulordrig.dir/src/net/Network.cpp.o
In file included from /var/tmp/ulordrig/src/workers/Workers.h:35:0,
                 from /var/tmp/ulordrig/src/net/Network.cpp:44:
/var/tmp/ulordrig/src/net/JobResult.h: 在成员函数‘uint64_t JobResult::actualDiff() const’中:
/var/tmp/ulordrig/src/net/JobResult.h:70:71: 警告：提领类型双关的指针将破坏强重叠规则 [-Wstrict-aliasing]
         return Job::toDiff(reinterpret_cast<const uint64_t*>(result)[3]);
                                                                       ^
[ 69%] Building CXX object CMakeFiles/ulordrig.dir/src/net/strategies/DonateStrategy.cpp.o
[ 70%] Building CXX object CMakeFiles/ulordrig.dir/src/net/strategies/FailoverStrategy.cpp.o
[ 72%] Building CXX object CMakeFiles/ulordrig.dir/src/net/strategies/SinglePoolStrategy.cpp.o
[ 73%] Building CXX object CMakeFiles/ulordrig.dir/src/net/SubmitResult.cpp.o
[ 75%] Building CXX object CMakeFiles/ulordrig.dir/src/net/Url.cpp.o
[ 76%] Building CXX object CMakeFiles/ulordrig.dir/src/Options.cpp.o
[ 78%] Building CXX object CMakeFiles/ulordrig.dir/src/Platform.cpp.o
[ 80%] Building CXX object CMakeFiles/ulordrig.dir/src/Summary.cpp.o
[ 81%] Building CXX object CMakeFiles/ulordrig.dir/src/workers/DoubleWorker.cpp.o
In file included from /var/tmp/ulordrig/src/workers/DoubleWorker.h:31:0,
                 from /var/tmp/ulordrig/src/workers/DoubleWorker.cpp:31:
/var/tmp/ulordrig/src/net/JobResult.h: 在成员函数‘uint64_t JobResult::actualDiff() const’中:
/var/tmp/ulordrig/src/net/JobResult.h:70:71: 警告：提领类型双关的指针将破坏强重叠规则 [-Wstrict-aliasing]
         return Job::toDiff(reinterpret_cast<const uint64_t*>(result)[3]);
                                                                       ^
/var/tmp/ulordrig/src/workers/DoubleWorker.cpp: 在成员函数‘virtual void DoubleWorker::start()’中:
/var/tmp/ulordrig/src/workers/DoubleWorker.cpp:92:57: 警告：提领类型双关的指针将破坏强重叠规则 [-Wstrict-aliasing]
             if (*reinterpret_cast<uint64_t*>(m_hash + 24) < m_state->job.target()) {
                                                         ^
/var/tmp/ulordrig/src/workers/DoubleWorker.cpp:96:62: 警告：提领类型双关的指针将破坏强重叠规则 [-Wstrict-aliasing]
             if (*reinterpret_cast<uint64_t*>(m_hash + 32 + 24) < m_state->job.target()) {
                                                              ^
[ 83%] Building CXX object CMakeFiles/ulordrig.dir/src/workers/Handle.cpp.o
[ 84%] Building CXX object CMakeFiles/ulordrig.dir/src/workers/Hashrate.cpp.o
[ 86%] Building CXX object CMakeFiles/ulordrig.dir/src/workers/SingleWorker.cpp.o
In file included from /var/tmp/ulordrig/src/workers/SingleWorker.h:31:0,
                 from /var/tmp/ulordrig/src/workers/SingleWorker.cpp:30:
/var/tmp/ulordrig/src/net/JobResult.h: 在成员函数‘uint64_t JobResult::actualDiff() const’中:
/var/tmp/ulordrig/src/net/JobResult.h:70:71: 警告：提领类型双关的指针将破坏强重叠规则 [-Wstrict-aliasing]
         return Job::toDiff(reinterpret_cast<const uint64_t*>(result)[3]);
                                                                       ^
[ 87%] Building CXX object CMakeFiles/ulordrig.dir/src/workers/Worker.cpp.o
[ 89%] Building CXX object CMakeFiles/ulordrig.dir/src/workers/Workers.cpp.o
In file included from /var/tmp/ulordrig/src/workers/DoubleWorker.h:31:0,
                 from /var/tmp/ulordrig/src/workers/Workers.cpp:32:
/var/tmp/ulordrig/src/net/JobResult.h: 在成员函数‘uint64_t JobResult::actualDiff() const’中:
/var/tmp/ulordrig/src/net/JobResult.h:70:71: 警告：提领类型双关的指针将破坏强重叠规则 [-Wstrict-aliasing]
         return Job::toDiff(reinterpret_cast<const uint64_t*>(result)[3]);
                                                                       ^
[ 90%] Building CXX object CMakeFiles/ulordrig.dir/src/ulordrig.cpp.o
[ 92%] Building CXX object CMakeFiles/ulordrig.dir/src/App_unix.cpp.o
[ 93%] Building CXX object CMakeFiles/ulordrig.dir/src/Cpu_unix.cpp.o
[ 95%] Building CXX object CMakeFiles/ulordrig.dir/src/Mem_unix.cpp.o
[ 96%] Building CXX object CMakeFiles/ulordrig.dir/src/Platform_unix.cpp.o
[ 98%] Building CXX object CMakeFiles/ulordrig.dir/src/Cpu.cpp.o
[100%] Building CXX object CMakeFiles/ulordrig.dir/src/log/SysLog.cpp.o
make[2]: *** 没有规则可以创建“ulordrig”需要的目标“/usr/lib/x86_64-linux-gnu/libcrypto.a”。 停止。
make[1]: *** [CMakeFiles/ulordrig.dir/all] 错误 2
make: *** [all] 错误 2

**Comment by jxinhu** [comment]
Modified，try again
