### ISSUE TITLE
Sudo yum groupinstall -y 'Development Tools'   报错

### ISSUE THREAD

**Issue by hozyu12** [UlordChain/UlordChain#25]
[root@Localhost wyb]# sudo yum groupinstall -y 'Development Tools'
已加载插件: fastestmirror, langpacks
没有安装组信息文件
Maybe run: yum groups mark convert(see man yum)
Loading mirror speeds from cached hostfile
* base: mirrors. aliyun. com
* extras: centos.ustc. edu. cn
* updates: centos. ustc. edu. cn
警告:分组组 deve Lopment不包含任何可安装软件包。
Maybe run:yum groups mark install (see man yum)
指定组中没有可安装或升级的软件包

**Comment by llbec** [comment]
@hozyu12 请问你的 sudo yum groupinstall -y 'Development Tools' 是哪里来的？

**Comment by hozyu12** [comment]
编译教程里有
   - CentOS 7

        # sudo yum update -y

        # sudo yum upgrade -y

        # sudo yum install -y libtool git cmake libmicrohttpd-devel openssl openssl-devel libstdc++-static

        # sudo yum groupinstall -y 'Development Tools'

**Comment by llbec** [comment]
@hozyu12 能把链接放上来吗？

**Comment by hozyu12** [comment]
@bicliu https://www.jianshu.com/p/920ae896ea3e?from=singlemessage&isappinstalled=0
在这，帮看一下。谢谢

**Comment by llbec** [comment]
@hozyu12 请参考官方挖矿软件的说明<https://github.com/UlordChain/ulordrig/wiki/CentOS-Build>

你看的那个链接，我们不知道是哪位爱好者发布的.....，建议你作为辅助参考即可。

这个问题我就关闭了，后续关于挖矿软件的问题你可以在<https://github.com/UlordChain/ulordrig.git>中进行探讨，谢谢！
