### ISSUE TITLE
请问如何创建一个钱包，以及如何把这个钱包加载到RPC便于矿池连接调用？

### ISSUE THREAD

**Issue by eeeeLeeee** [UlordChain/UlordChain#27]
请问如何创建一个钱包，以及如何把这个钱包加载到RPC便于矿池连接调用？

**Comment by lialvin** [comment]
全节点自带钱包功能，rpc命令可以直接用，官网有搭建矿池教程

**Comment by eeeeLeeee** [comment]
确实没找到搭建矿池的教程，github上那个md文件也不是很详细，可否给个地址？

**Comment by jxinhu** [comment]
编译ulordchain生成ulord daemon程序后，按照矿池所需配置运行daemon，再在矿池的配置文件中添加daemon的ip、port和rpcuser等信息
