### ISSUE TITLE
如何做到这种远超普通电脑cpu的算力？

### ISSUE THREAD

**Issue by 3389** [UlordChain/UlordChain#29]
![Markdown](http://i1.bvimg.com/610066/4c7c3b2bc1fe4c71.png)

**Comment by 3389** [comment]
显示只有2台机子但是算力逆天

**Comment by taylorshuang** [comment]
这种情况是有的，将很多矿机采用同一个钱包地址，但不进行编号，这样看起来就是一台大矿机
