### ISSUE TITLE
官网无法访问

### ISSUE THREAD

**Issue by guzhenping** [UlordChain/UlordChain#3]
官网无法访问，https://www.ulord.org

**Comment by dpingk** [comment]
Visit [ulord](ulord.net), plz.

**Comment by guzhenping** [comment]
ulord.net上面的钱包无法现在？why?

**Comment by taylorshuang** [comment]
Their official website is http://ulord.org/

**Comment by guzhenping** [comment]
我觉得在解析DNS时，没加上www, 然后把它公开了
