### ISSUE TITLE
linux 怎么给每台机子编号，现在显示的noname

### ISSUE THREAD

**Issue by zhjgit** [UlordChain/UlordChain#30]
看了帮助文档，还是没明白怎么设置
![_20180528182228](https://user-images.githubusercontent.com/11417141/40610228-22b91c4e-62a4-11e8-9a77-18fe612dfa60.png)

**Comment by zhjgit** [comment]
Usage: Ulordrig [OPTIONS]
Options:
  -o, --url=URL            URL of mining server
  -O, --userpass=U:P       username:password pair for mining server
  -u, --user=USERNAME      username for mining server
  -p, --pass=PASSWORD      password for mining server
  -t, --threads=N          number of miner threads
  -v, --av=N               algorithm variation, 0 auto select
  -k, --keepalive          send keepalived for prevent timeout (need pool support)
  -r, --retries=N          number of times to retry before switch to backup server (default: 5)
  -R, --retry-pause=N      time to pause between retries (default: 5)
      --cpu-affinity       set process affinity to CPU core(s), mask 0x3 for cores 0 and 1
      --cpu-priority       set process priority (0 idle, 2 normal to 5 highest)
      --no-huge-pages      disable huge pages support
      --no-color           disable colored output
      --variant            algorithm PoW variant
      --user-agent         set custom user-agent string for pool
  -B, --background         run the miner in the background
  -c, --config=FILE        load a JSON-format configuration file
  -l, --log-file=FILE      log all output to a file
  -S, --syslog             use system log for output messages
      --max-cpu-usage=N    maximum CPU usage for automatic threads mode (default 75)
      --safe               safe adjust threads and av settings for current CPU
      --nicehash           enable nicehash/ulordrig-proxy support
      --print-time=N       print hashrate report every N seconds
      --api-port=N         port for the miner API
      --api-access-token=T access token for API
      --api-worker-id=ID   custom worker-id for API
  -h, --help               display this help and exit
  -V, --version            output version information and exit
官方提供的命令选项是这些，唯一可能的是  --user-agent  但是设置了  --user-agent “test01” 还是不显示

**Comment by jxinhu** [comment]
<https://github.com/UlordChain/ulordrig/issues/5>
<https://github.com/UlordChain/ulordrig/issues/16>
