### ISSUE TITLE
/usr/include/boost/filesystem/operations.hpp:381: undefined reference to `boost::filesystem::detail::copy_file

### ISSUE THREAD

**Issue by thor830428** [UlordChain/UlordChain#9]
AR       libbitcoin_wallet.a
  CXXLD    ulordd
libbitcoin_wallet.a(libbitcoin_wallet_a-walletdb.o): In function `copy_file':
/usr/include/boost/filesystem/operations.hpp:381: undefined reference to `boost::filesystem::detail::copy_file(boost::filesystem::path const&, boost::filesystem::path const&, boost::filesystem::copy_option, boost::system::error_code*)'
/usr/include/boost/filesystem/operations.hpp:384: undefined reference to `boost::filesystem::detail::copy_file(boost::filesystem::path const&, boost::filesystem::path const&, boost::filesystem::copy_option, boost::system::error_code*)'
collect2: error: ld returned 1 exit status
make[2]: *** [ulordd] Error 1
make[2]: Leaving directory `/home/ulord/ulordchain/UlordChain/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/ulord/ulordchain/UlordChain/src'
make: *** [all-recursive] Error 1

**Comment by AlfredZKY** [comment]
Do you use the Linux system or ubuntu 16.04 to compile? Please strictly follow the READ.md instructions to build the dependency environment, and then compile and install.

**Comment by AlfredZKY** [comment]
close
